Repository quarkus-qe/quarkus-test-suite, pull requests merged in 2024-10, with the labels that each got.

#2059 Enable funqy tests in Native
  funqy/knative-events/pom.xml
  funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/FunqyKnEventsIT.java
  funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/ServerlessExtensionOpenShiftFunqyKnEventsIT.java
Labels: triage/backport-3.15

#2066 Disable SSL requirement for keycloak realms
  security/keycloak-oidc-client-extended/src/test/resources/kc-logout-realm.json
  security/keycloak-oidc-client-reactive-extended/src/test/resources/kc-logout-realm.json
Labels: triage/backport-3.15

#2073 Disable OpenShiftDefaultInitContainerIT on aarch64
  sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/OpenShiftDefaultInitContainerIT.java
Labels: triage/backport-3.15

#2070 [3.15] Update framework and Quarkus to the latest versions
  .github/workflows/ci.yml
  pom.xml
Labels: triage/flaky-test

#2075 Fix PostgresqlResource which failing to start when using RH postgres image
  sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/dbpool/PostgresqlResource.java
Labels: triage/backport-3.15

#2077 Disable kafka streams test also on quarkus main aarch native
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnAarch64Native.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnAarch64NativeConditions.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
Labels: triage/flaky-test, triage/backport-3.15

#2080 Fix failures in CLI
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
Labels: triage/backport-3.15

#2083 Check kafka metrics independently from their order
  monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/BaseOpenShiftAlertEventsIT.java
Labels: triage/backport-3.15

#2084 Bump test framework to 1.6.0.Beta11
  pom.xml
Labels: triage/flaky-test

#2087 Do not mix --platform and --stream options for CLI
  build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
Labels: triage/backport-3.15

#2086 Use DisabledOnAarch64Native annotation from framework
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnAarch64Native.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnAarch64NativeConditions.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
Labels: triage/flaky-test, triage/backport-3.15

#2081 Disable kafka snappy tests on aarch64 native
  messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/OpenShiftKafkaSnappyIT.java
  messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/SnappyCompressionIT.java
Labels: triage/backport-3.15

#2088 Change netty-native-epoll classifier to work on aarch
  http/http-advanced/pom.xml
Labels: triage/backport-3.15

#2094 Add QUARKUS-4612 workaround to nosql/infinispan
  nosql-db/infinispan/src/main/resources/application.properties
  nosql-db/infinispan/src/test/resources/infinispan-it.properties
Labels: triage/backport-3.15

#2097 Fix TLS MSSQL test in FIPS-enabled environment and disable non-TLS MSSQL tests in FIPS-enabled environment
  sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MsSQLDatabaseHibernateReactiveIT.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
  sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MssqlPanacheResourceIT.java
  sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMssqlDevServiceUserExperienceIT.java
  sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MssqlDatabaseIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MssqlDatabaseIT.java
  sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java
Labels: triage/backport-3.15

#2098 Drop @IfBuildProfile from injection points in VertX SQL module as it has no function at all
  sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/Application.java
Labels: triage/backport-3.15

#2100 Disable ConfigIT in native in FIPS-enabled environment due to Mandrel bug
  config/src/test/java/io/quarkus/ts/configmap/api/server/ConfigIT.java
  config/src/test/java/io/quarkus/ts/configmap/api/server/DisabledOnFipsAndNative.java
  config/src/test/java/io/quarkus/ts/configmap/api/server/DisabledOnFipsAndNativeCondition.java
Labels: triage/backport-3.15

#2099 Disable BCFIPS in native in FIPS-enabled env as not supported
  security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/BouncyCastleFipsIT.java
  security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/DisabledOnFipsAndNative.java
  security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/DisabledOnFipsAndNativeCondition.java
Labels: triage/backport-3.15

#2092 Introduce podman property podman-disabled in build/podman
  build/podman/pom.xml
Labels: triage/flaky-test

#2102 Add porperty quarkus.bild.skip podman-disabled
  build/podman/pom.xml
Labels: triage/backport-3.15

#2067 Fix not enough space error for keycloak container image quay.io/keycloak/keycloak:25.0
  http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
Labels: triage/flaky-test

#2119 Add access logging tests
  logging/jboss/src/main/java/io/quarkus/ts/logging/jboss/AccessResource.java
  logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/AccessLoggingIT.java
  logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/DefaultMinLogLevelIT.java
  logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/LoggingInJsonIT.java
  logging/jboss/src/test/resources/accessLogging.properties
  logging/jboss/src/test/resources/default.properties
Labels: triage/backport-3.15

#2113 Add version suffix to docker images
  pom.xml
Labels: triage/flaky-test

#2127 Overwrite images also in surefire plugin
  pom.xml
Labels: triage/backport-3.8, triage/backport-3.15

#2135 Configure postgres transaction separately for images
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageCommunity.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageCommunityCondition.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageProduct.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageProductCondition.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/PostgresqlCommunityTransactionGeneralUsageIT.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/PostgresqlProductTransactionGeneralUsageIT.java
Labels: triage/backport-3.8, triage/backport-3.15

#2145 Make nginx proxy resolver configurable
  http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientProxyIT.java
  http/rest-client-reactive/src/test/resources/nginx.conf.template
  pom.xml
Labels: triage/backport-3.15

#2147 Use Docker PostgreSQL image from Docker.io and not from Red Hat registry in Dev Service tests on Aarch64
  pom.xml
  sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactivePostgresqlDevServiceUserExperienceIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlDevServiceUserExperienceIT.java
Labels: triage/backport-3.15

#2148 Fix DevModeInfinispanIT on Aarch64 platform as only image from Red Hat registry is supported for this platform
  nosql-db/infinispan/src/test/java/io/quarkus/ts/infinispan/DevModeInfinispanIT.java
  pom.xml
Labels: triage/backport-3.15

#2149 Disabling Kafka Streams tests due to QUARKUS-4321
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SaslSslAlertMonitorIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/StrimziKafkaStreamIT.java
Labels: triage/backport-3.15

#2150 Disable SSL and SASL_SSL Kafka and Infinispan tests in FIPS-enabled environment in native mode
  messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaIT.java
  messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaSaslSslIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SaslSslAlertMonitorIT.java
  messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSaslSslIT.java
  messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSaslSslTlsRegistryIT.java
Labels: triage/flaky-test, triage/backport-3.15
