Repository quarkus-qe/quarkus-test-suite, pull requests merged in 2024-09, with the labels that each got.

#1961 Reduce log size in CI runs
  .github/workflows/ci.yml
  .github/workflows/daily.yaml
Labels: triage/backport-3.8, triage/flaky-test, backport-3.15

#1970 Ensure Kafka version is visible in metrics, especially in native mode
  monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/KafkaAndMetricsIT.java
Labels: triage/backport-3.8, triage/backport-3.15, BACKPORT CAREFULLY

#1962 Ensure abstract jakarta.ws.rs.core.Application is ignored
  http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/AbstractApplication.java
  http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/AbstractApplication.java
Labels: triage/backport-3.8, triage/backport-3.15

#1963 Test Quarkus REST abstract resources with @Path
  http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/GreetingAbstractResource.java
  http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/GreetingResource.java
  http/http-advanced-reactive/src/main/resources/application.properties
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
Labels: triage/backport-3.8, triage/backport-3.15, BACKPORT CAREFULLY

#1968 Make sure AsyncFile gets closed
  http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/DownloadResource.java
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DownloadResourceIT.java
Labels: triage/backport-3.8, triage/backport-3.15

#1949 Test coverage for ensuring the MessageBodyWriter is used with null Accept header
  http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/CustomHeaderResponse.java
  http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/HeadersMessageBodyWriter.java
  http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/HeadersResource.java
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HeadersIT.java
  http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/CustomHeaderResponse.java
  http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/HeadersMessageBodyWriter.java
  http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/HeadersResource.java
  http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HeadersIT.java
Labels: triage/backport-3.8, triage/backport-3.15

#1976 Dont configure HTTPS in security Vert.X JWT tests
  security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/AbstractCommonIT.java
Labels: triage/backport-3.15

#1981 Disable podman build on Openshift runs
  build/podman/pom.xml
Labels: triage/backport-3.15

#1972 Verify fault tolerance with rest client reactive
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/HeaderResource.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RequestIdClientRequestFilter.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RequestIdContainerRequestFilter.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RequestIdManager.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RequestIdManagerImpl.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RetryClient.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/ServerRetryResource.java
  http/rest-client-reactive/src/main/resources/application.properties
  http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientRetryIT.java
Labels: DON'T MERGE, triage/backport-3.8, triage/backport-3.15

#1982 Add Quarkus CLI TLS command test coverage
  quarkus-cli/pom.xml
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliTlsCommandIT.java
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/tls/surefire/TlsCommandTest.java
Labels: triage/backport-3.15

#1977 Add TLS registry tests for gRPC server and client and drop hardcoded certificates in favor of generated ones
  http/grpc/src/main/java/io/quarkus/ts/http/grpc/GrpcReflectionResponse.java
  http/grpc/src/main/resources/application.properties
  http/grpc/src/main/resources/tls/ca.cnf
  http/grpc/src/main/resources/tls/ca.pem
  http/grpc/src/main/resources/tls/server.key
  http/grpc/src/main/resources/tls/server.pem
  http/grpc/src/test/java/io/quarkus/ts/http/grpc/GRPCIT.java
  http/grpc/src/test/java/io/quarkus/ts/http/grpc/GrpcMutualTlsSeparateServerIT.java
  http/grpc/src/test/java/io/quarkus/ts/http/grpc/GrpcTlsSeparateServerIT.java
  http/grpc/src/test/java/io/quarkus/ts/http/grpc/OpenShiftExtensionGRPCIT.java
  http/grpc/src/test/java/io/quarkus/ts/http/grpc/OpenShiftGRPCIT.java
  http/grpc/src/test/java/io/quarkus/ts/http/grpc/ReflectionHttpIT.java
  http/grpc/src/test/java/io/quarkus/ts/http/grpc/SameServerIT.java
  http/grpc/src/test/java/io/quarkus/ts/http/grpc/SeparateServerIT.java
  http/grpc/src/test/java/io/quarkus/ts/http/grpc/StreamingHttpIT.java
  http/grpc/src/test/java/io/quarkus/ts/http/grpc/TLSIT.java
Labels: triage/backport-3.15

#1984 Properly disable the build of podman on openshift
  build/podman/pom.xml
Labels: triage/backport-3.15

#1986 Test Mutual TLS with Management interface configured using TLS Registry extension and certificate reloading
  http/management/src/main/java/io/quarkus/qe/ManagementRoute.java
  http/management/src/test/java/io/quarkus/qe/MutualTlsManagementInterfaceIT.java
Labels: triage/backport-3.15

#1987 Test OpenShift serving certificates and TLS registry with REST client
  http/rest-client-reactive/src/test/java/hero/Hero.java
  http/rest-client-reactive/src/test/java/hero/HeroClient.java
  http/rest-client-reactive/src/test/java/hero/HeroClientResource.java
  http/rest-client-reactive/src/test/java/hero/HeroResource.java
  http/rest-client-reactive/src/test/java/hero/Villain.java
  http/rest-client-reactive/src/test/java/hero/VillainClient.java
  http/rest-client-reactive/src/test/java/hero/VillainClientResource.java
  http/rest-client-reactive/src/test/java/hero/VillainResource.java
  http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/OpenShiftServingCertificatesIT.java
  http/rest-client-reactive/src/test/resources/certificate-serving-client.properties
  http/rest-client-reactive/src/test/resources/certificate-serving-server.properties
Labels: triage/backport-3.15

#1988 Test OpenTelemetry integration with TLS registry and exporting traces using secured channel
  monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryManagementIT.java
Labels: triage/backport-3.15

#1994 Switch to supported service type
  infinispan-client/src/test/resources/infinispan_cluster_config.yaml
Labels: triage/backport-3.8, triage/backport-3.15

#1996 [3.15] Turn openshift-arm profile into general aarch64
  README.md
  pom.xml
Labels: triage/flaky-test

#1991 Added isRHBQ method to check if the version contains string redhat
  build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQAarch64NativeConditions.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQWindowsConditions.java
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
Labels: triage/flaky-test

#2007 Revert "Change waiting strategy for PG imgs from RH registry till FW is fixed"
  external-applications/src/test/java/io/quarkus/ts/external/applications/AbstractTodoDemoIT.java
  external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftTodoDemoIT.java
  external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
  external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
  external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
  spring/spring-data/src/test/java/io/quarkus/ts/spring/data/AbstractDbIT.java
  sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/openshift/OpenShiftPostgresqlHibernateReactiveIT.java
  sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/OpenShiftMultiplePersistenceIT.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftPostgresqlTransactionGeneralUsageIT.java
  sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/OpenShiftPostgresqlPanacheResourceIT.java
  sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/PostgresqlPanacheResourceIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftPostgresqlDatabaseIT.java
Labels: triage/backport-3.15

#2021 Excluding DB2 tests from aarch64 profile
  sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/DB2DatabaseIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DB2DatabaseIT.java
Labels: triage/backport-3.15

#2019 Excluding MS SQL tests from aarch64 profile
  sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MsSQLDatabaseHibernateReactiveIT.java
  sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/openshift/OpenShiftHibernateReactiveMsSQLIT.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMssqlTransactionGeneralUsageIT.java
  sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MssqlPanacheResourceIT.java
  sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/OpenShiftMssqlPanacheResourceIT.java
  sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeMultipleReactiveSqlClientsIT.java
  sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMssqlDevServiceUserExperienceIT.java
  sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MssqlDatabaseIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MssqlDatabaseIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMssqlDatabaseIT.java
  sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java
Labels: triage/backport-3.15

#2023 Excluding Oracle tests from aarch64 profile
  security/jpa/src/test/java/io/quarkus/ts/security/jpa/OraclePlaintextExternalRolesJpaIT.java
  security/jpa/src/test/java/io/quarkus/ts/security/jpa/OracleSha512JpaIT.java
  sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/OracleDatabaseIT.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OracleTransactionGeneralUsageIT.java
  sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/OraclePanacheResourceIT.java
  sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/OracleDatabaseIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleDevServiceUserExperienceIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OracleDatabaseIT.java
  sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/OracleHandlerIT.java
Labels: triage/backport-3.15

#2026 Disable tests missing aarch64 test services
  logging/thirdparty/src/test/java/io/quarkus/ts/logging/jboss/SyslogIT.java
  spring/spring-cloud-config/src/test/java/io/quarkus/ts/spring/cloud/config/SpringCloudConfigIT.java
Labels: triage/backport-3.15

#2029 TS cleanup
  build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/CliProdModeNativeIT.java
  build/docker/src/test/java/io/quarkus/ts/docker/DockerBuildIT.java
  config/src/main/resources/application.properties
  config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftConfigSourcePriorityIT.java
  config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftFailOnMissingConfigIT.java
  funqy/knative-events/pom.xml
  funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/FunqyKnEventsIT.java
  funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/ServerlessExtensionOpenShiftFunqyKnEventsIT.java
  http/graphql/src/test/java/io/quarkus/ts/http/graphql/GraphQLDisabledGetIT.java
  http/graphql/src/test/java/io/quarkus/ts/http/graphql/OpenShiftGraphQLDisabledGetIT.java
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/Brotli4JHttpIT.java
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HttpAdvancedReactiveIT.java
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftBrotli4JIT.java
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHttpAdvancedReactiveIT.java
  http/http-advanced-reactive/src/test/resources/compression.properties
  http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DomainSocketIT.java
  http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
  http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/OpenShiftHttpAdvancedIT.java
  http/rest-client-reactive/pom.xml
  messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/CertUtils.java
  messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaIT.java
  messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaSaslSslIT.java
  messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/DevModeKafkaSnappyIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/KafkaGratefulShutdownIT.java
  messaging/kafka-strimzi-avro-reactive-messaging/src/main/resources/application.properties
  monitoring/micrometer-prometheus-oidc/src/test/java/io/quarkus/ts/micrometer/oidc/BaseMicrometerOidcSecurityIT.java
  monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftCustomMetricsIT.java
  pom.xml
  security/keycloak-authz-classic/src/test/java/io/quarkus/ts/security/keycloak/authz/KeycloakAuthzSecurityIT.java
  security/keycloak-authz-reactive/src/test/java/io/quarkus/ts/security/keycloak/authz/reactive/KeycloakAuthzSecurityReactiveIT.java
  security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/KeycloakOidcJwtSecurityIT.java
  security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/KeycloakMultiTenantSecurityIT.java
  security/keycloak-oauth2/src/test/java/io/quarkus/ts/security/keycloak/oauth2/KeycloakOauth2SecurityIT.java
  security/keycloak-oidc-client-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/basic/KeycloakOidcClientSecurityIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/BaseOidcIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/LogoutSinglePageAppFlowIT.java
  security/keycloak-oidc-client-reactive-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/basic/KeycloakOidcClientSecurityIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/BaseOidcIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/LogoutSinglePageAppFlowIT.java
  security/keycloak-webapp/src/test/java/io/quarkus/ts/security/keycloak/webapp/KeycloakWebappSecurityIT.java
  security/keycloak/src/main/resources/application.properties
  security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/DevModeOidcSecurityIT.java
  security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/KeycloakOidcSecurityIT.java
  security/oidc-client-mutual-tls/src/main/resources/application.properties
  security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/IncorrectKsFileTypeOidcMtlsIT.java
  security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/JksOidcMtlsIT.java
  security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/MutualTlsKeycloakService.java
  security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/OpenShiftRhSsoOidcMtlsIT.java
  sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/AbstractDatabaseHibernateReactiveIT.java
  sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/OpenShiftDefaultInitContainerIT.java
  sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/OpenShiftFlywayInitContainerIT.java
Labels: triage/flaky-test, triage/backport-3.15

#2003 Add coverage for quarkus-picocli
  pom.xml
  quarkus-picocli/pom.xml
  quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/AgeCommand.java
  quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/CommonOptions.java
  quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/EntryCommand.java
  quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/HelloCommand.java
  quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/OtherCommand.java
  quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/OtherEntryCommand.java
  quarkus-picocli/src/main/java/io/quarkus/ts/qe/configuration/Config.java
  quarkus-picocli/src/main/java/io/quarkus/ts/qe/services/AgeService.java
  quarkus-picocli/src/main/java/io/quarkus/ts/qe/services/HelloService.java
  quarkus-picocli/src/test/java/PicocliDevIT.java
  quarkus-picocli/src/test/java/PicocliProdIT.java
  quarkus-picocli/src/test/resources/dev.properties
  quarkus-picocli/src/test/resources/prod.properties
Labels: triage/flaky-test, triage/backport-3.15

#2042 Fix QuarkusCliTlsCommandIT truststore config property value on Windows
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliTlsCommandIT.java
Labels: triage/backport-3.15

#2039 Fix OpenTelemetryManagementIT on Windows (when Linux containers are available) by porting remote Docker agent to localhost
  monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/JaegerLocalhostDockerManagerResource.java
  monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryManagementIT.java
Labels: triage/backport-3.15

#2041 Fix DevModeMultipleReactiveSqlClientsIT on Aarch64 by switching MSSQL for MariaDB
  sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/HardCoverBookResource.java
  sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/ReactiveClientConverter.java
  sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/model/HardCoverBook.java
  sql-db/reactive-vanilla/src/main/resources/application.properties
  sql-db/reactive-vanilla/src/main/resources/mariadb-init-script.sql
  sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeMultipleReactiveSqlClientsIT.java
  sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMssqlDevServiceUserExperienceIT.java
  sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMysqlDevServiceUserExperienceIT.java
  sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactivePostgresqlDevServiceUserExperienceIT.java
Labels: triage/backport-3.15

#2045 Improve flakiness reporting by storing flaky run report with failed test name and failure message
  .github/workflows/ci.yml
Labels: triage/flaky-test
