Repository quarkus-qe/quarkus-test-suite, pull requests merged in 2024-11, with the labels that each got.

#2154 Remove property JAVA_OPT_KC_HEAP
  http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
Labels: triage/backport-3.15

#2165 Disable ManyExtensionsIT on FIPS in native mode
  super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ManyExtensionsIT.java
Labels: triage/backport-3.15

#2167 Fix `AccessLoggingIT` when test is executed with long working directory path
  logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/AccessLoggingIT.java
Labels: triage/backport-3.15

#2173 Allow wait container to run on different architectures
  sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/OpenShiftDefaultInitContainerIT.java
  sql-db/panache-flyway/src/test/resources/build.sh
Labels: triage/flaky-test, triage/backport-3.15

#2177 Update disable reason for Kafka streams on aarch64
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SaslSslAlertMonitorIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/StrimziKafkaStreamIT.java
Labels: triage/backport-3.8, triage/flaky-test, triage/backport-3.15

#2183 Add test for @RestForm Map<String, String> handling in REST Client
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainBookResource.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/ReactiveClientBookResource.java
  http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
Labels: triage/backport-3.15

#2186 Add coverage for Quarkus #43422
  http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/GreetingInterface.java
  http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/GreetingOptionAndHeadResource.java
  http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/GreetingSubResources.java
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
Labels: triage/backport-3.15

#2195 Run SpringCloudConfigIT on Aarch64
  spring/spring-cloud-config/src/test/java/io/quarkus/ts/spring/cloud/config/SpringCloudConfigIT.java
Labels: triage/backport-3.15

#2190 Apply idea code analysis suggestions M-N
  messaging/infinispan-grpc-kafka/README.md
  messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanPopulated.java
  messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/books/BookCacheInitializer.java
  messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/books/BookContextInitializer.java
  messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/books/BookResource.java
  messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/prices/PriceGenerator.java
  messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/quickstart/KafkaEndpoint.java
  messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/BaseKafkaAvroGroupIdIT.java
  messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/producer/Application.java
  messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/producer/FailureHandler.java
  messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/producer/KafkaBlockingProducer.java
  messaging/kafka-streams-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/reactive/streams/aggregator/streams/WindowedLoginDeniedStream.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeRedPandaDevServiceUserExperienceIT.java
  messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/BaseKafkaAvroGroupIdIT.java
  messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/quickstart/KafkaEndpoint.java
  messaging/qpid/src/main/java/io/quarkus/ts/messaging/qpid/PriceConsumer.java
  monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/BaseOpenShiftAlertEventsReactiveIT.java
  monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/KafkaAndMetricsIT.java
  monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/BaseOpenShiftAlertEventsIT.java
  monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftCustomMetricsIT.java
  monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetryGrpcIT.java
  monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetrySseIT.java
  monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryGrpcIT.java
  monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetrySseIT.java
  nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/DataTypesService.java
  nosql-db/elasticsearch/src/test/java/io/quarkus/ts/elasticsearch/DevModeElasticsearchIT.java
  nosql-db/elasticsearch/src/test/java/io/quarkus/ts/elasticsearch/ElasticsearchIT.java
  nosql-db/infinispan/src/main/java/io/quarkus/ts/infinispan/client/InfinispanClientApp.java
  nosql-db/mongodb-reactive/src/main/java/io/quarkus/ts/nosqldb/mongodb/reactive/Fruit.java
  nosql-db/mongodb/src/main/java/io/quarkus/ts/nosqldb/mongodb/Fruit.java
Labels: triage/flaky-test

#2194 Apply idea code analysis suggestions Service*-End
  spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataCompositeEntityIT.java
  spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataSimpleEntityIT.java
  spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/AbstractPagingAndSortingRepositoryRestResourceIT.java
  spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/CrudRepositoryRestResourceIT.java
  spring/spring-properties/src/main/java/io/quarkus/ts/spring/properties/CollectionsController.java
  spring/spring-properties/src/main/java/io/quarkus/ts/spring/properties/ValueController.java
  spring/spring-properties/src/test/java/io/quarkus/ts/spring/properties/SpringPropertiesIT.java
  spring/spring-web-reactive/src/main/java/io/quarkus/ts/spring/web/reactive/bootstrap/persistence/model/Book.java
  spring/spring-web-reactive/src/main/java/io/quarkus/ts/spring/web/reactive/bootstrap/web/BookController.java
  spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/AbstractSpringWebRestReactiveIT.java
  spring/spring-web/src/main/java/io/quarkus/ts/spring/web/bootstrap/persistence/model/Book.java
  spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/AbstractSpringWebRestIT.java
  sql-db/hibernate-fulltext-search/src/main/java/io/quarkus/ts/hibernate/search/MyCustomIdGenerator.java
  sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/MysqlMultitenantHibernateSearchIT.java
  sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/BookDescription.java
  sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/GroundedEndpoint.java
  sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/PanacheEndpoint.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMariaDbTransactionGeneralUsageIT.java
  sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/ApplicationQueryResource.java
  sql-db/reactive-rest-data-panache/src/main/java/io/quarkus/ts/reactive/rest/data/panache/ApplicationQueryResource.java
  sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/AbstractSqlDatabaseIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/AbstractSqlDatabaseIT.java
  sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/Application.java
  sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/services/DbPoolService.java
  super-size/many-extensions/src/main/java/io/quarkus/ts/many/extensions/Hello.java
  test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ConsumerPactTest.java
Labels: triage/flaky-test

#2188 Add test coverage for #43364 - InputStream when using multipart
  http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MultipartResource.java
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/MultipartInputstreamIT.java
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftMultipartInputstreamIT.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/FileUploadClient.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/MultipartBodyWithMediaType.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/MultipartBodyWithoutMediaType.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/FileUploadClientTestResource.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/FileUploadResource.java
  http/rest-client-reactive/src/main/resources/modern.properties
  http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
Labels: triage/flaky-test

#2202 [3.15] 3.15 Backport Enable kafka tests on aarch64 for test coverage issue #43319
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SaslSslAlertMonitorIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/StrimziKafkaStreamIT.java
Labels: triage/flaky-test

#2207 Fix flaky KafkaGratefulShutdownIT by waiting until messaging channels are ready
  messaging/kafka-streams-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/reactive/streams/shutdown/ReadinessObserver.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/KafkaGratefulShutdownIT.java
  messaging/kafka-streams-reactive-messaging/src/test/resources/kafka.grateful.shutdown.application.properties
Labels: triage/backport-3.15

#2211 Fix flaky `OpentelemetryReactiveIT#testSecurityEvents` test
  monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
Labels: triage/backport-3.15

#2204 Add coverage for @CacheResult with resteasy client to cover QUARKUS-5068
  README.md
  cache/caffeine-resteasy/pom.xml
  cache/caffeine-resteasy/src/main/java/io/quarkus/ts/cache/caffeine/restclient/ClientBookResource.java
  cache/caffeine-resteasy/src/main/java/io/quarkus/ts/cache/caffeine/restclient/RestInterface.java
  cache/caffeine-resteasy/src/main/java/io/quarkus/ts/cache/caffeine/restclient/types/Book.java
  cache/caffeine-resteasy/src/main/java/io/quarkus/ts/cache/caffeine/restclient/types/BookAsJsonResource.java
  cache/caffeine-resteasy/src/main/java/io/quarkus/ts/cache/caffeine/restclient/types/BookAsXmlResource.java
  cache/caffeine-resteasy/src/main/resources/application.properties
  cache/caffeine-resteasy/src/test/java/io/quarkus/ts/cache/caffeine/restclient/OpenShiftRestClientWithCacheIT.java
  cache/caffeine-resteasy/src/test/java/io/quarkus/ts/cache/caffeine/restclient/RestClientWithCacheIT.java
  pom.xml
Labels: triage/backport-3.8, triage/backport-3.15

#2218 Add test to verify missing servlet-class in web.xml doesn't cause build failure with Undertow
  http/servlet-undertow/src/test/java/io/quarkus/ts/http/undertow/UndertowMissingServletClassIT.java
  http/servlet-undertow/src/test/java/io/quarkus/ts/http/undertow/WithMissingServlet.java
  http/servlet-undertow/src/test/resources/META-INF/invalid-web.xml
Labels: triage/backport-3.15

#2220 Add coverage for ArC fix when a framework bean uses the decorator
  README.md
  messaging/kafka-processor/pom.xml
  messaging/kafka-processor/src/main/java/io/quarkus/ts/messaging/kafka/processor/decorator/HeaderDecorator.java
  messaging/kafka-processor/src/main/java/io/quarkus/ts/messaging/kafka/processor/processor/PingProcessor.java
  messaging/kafka-processor/src/main/resources/application.properties
  messaging/kafka-processor/src/test/java/io/quarkus/ts/messaging/kafka/processor/DevModeKafkaProcessorIT.java
  pom.xml
Labels: triage/backport-3.15, BACKPORT CAREFULLY

#2227 Raise the buffer for max file size to fix run on jenkins
  logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/AccessLoggingIT.java
Labels: triage/backport-3.15
