Repository quarkus-qe/quarkus-test-suite, pull requests merged in 2024-12, with the labels that each got.

#2238 Fix QuarkusCli35to315UpdateIT
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/QuarkusCli35to315UpdateIT.java
Labels: triage/backport-3.15

#2245 Remane vectorized/redpanda to redpandadata/redpanda as the name was realocated
  messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/DevModeKafkaSnappyIT.java
  messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeKafkaStreamIT.java
Labels: triage/backport-3.8, triage/backport-3.15

#2237 Dissable the testHttp10WithoutHostHeader on openshift
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHeadersIT.java
Labels: triage/backport-3.15

#2254 Add coverage for "method not registered" error in native mode
  http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/JakartaRestInterceptor.java
  http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/Operator.java
  http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/OperatorResource.java
  http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
Labels: triage/flaky-test
