Repository quarkus-qe/quarkus-test-suite, pull requests merged in 2024-08, with the labels that each got.

#1910 Updating PR CI to run full native if no changes in modules are detected
  .github/workflows/ci.yml
  .github/workflows/daily.yaml
Labels: triage/backport-3.2, triage/backport-3.8, triage/flaky-test

#1914 Add coverage for Infinispan cache extension
  README.md
  cache/infinispan/pom.xml
  cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/ApplicationScopeService.java
  cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/BaseServiceWithCache.java
  cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/BlockingWithCacheResource.java
  cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/CacheExpirationResource.java
  cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/ReactiveWithCacheResource.java
  cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/RequestScopeService.java
  cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/ServiceWithCacheResource.java
  cache/infinispan/src/main/resources/application.properties
  cache/infinispan/src/test/java/io/quarkus/ts/cache/infinispan/InfinispanCacheIT.java
  cache/infinispan/src/test/java/io/quarkus/ts/cache/infinispan/OpenShiftInfinispanCacheIT.java
  cache/infinispan/src/test/resources/test.properties
  pom.xml
Labels: triage/backport-3.8, triage/flaky-test

#1919 Reproducer for leaking connection in XA mode
  .github/workflows/ci.yml
  README.md
  sql-db/narayana-transactions/src/main/java/io/quarkus/ts/service/ServiceResource.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
Labels: triage/backport-3.8

#1916 Feature/podman build
  README.md
  build/docker/pom.xml
  build/docker/src/main/docker/Dockerfile.jvm
  build/docker/src/main/docker/Dockerfile.native
  build/docker/src/main/java/io/quarkus/ts/docker/HelloResource.java
  build/docker/src/main/resources/application.properties
  build/docker/src/test/java/io/quarkus/ts/docker/DockerBuildIT.java
  build/docker/src/test/java/io/quarkus/ts/docker/NativeConfigurationIT.java
  build/podman/pom.xml
  build/podman/src/main/docker/Dockerfile.jvm
  build/podman/src/main/docker/Dockerfile.native
  build/podman/src/main/java/io/quarkus/ts/docker/HelloResource.java
  build/podman/src/main/resources/application.properties
  build/podman/src/test/java/io/quarkus/ts/docker/PodmanBuildIT.java
  pom.xml
Labels: triage/flaky-test

#1940 Update `root-modules-no-qute` profile modules
  pom.xml
Labels: triage/flaky-test
