Repository quarkus-qe/quarkus-test-suite, pull requests merged in 2025-04, with the labels that each got.

#2370 Set fail-fast to false in CI for PRs
  .github/workflows/ci.yml
Labels: triage/backport-3.15, triage/backport-3.20

#2356 Add websocket next tests
  README.md
  pom.xml
  websockets/websocket-next-oidc/pom.xml
  websockets/websocket-next-oidc/src/main/java/io/quarkus/ts/websocketNext/endpoints/AdminChatWebSocket.java
  websockets/websocket-next-oidc/src/main/java/io/quarkus/ts/websocketNext/endpoints/AuthenticatedWebSocket.java
  websockets/websocket-next-oidc/src/main/java/io/quarkus/ts/websocketNext/resources/AuthenticatedChatResource.java
  websockets/websocket-next-oidc/src/main/resources/application.properties
  websockets/websocket-next-oidc/src/test/java/io/quarkuss/ts/websocketNext/OidcWebSocketIT.java
  websockets/websocket-next-oidc/src/test/java/io/quarkuss/ts/websocketNext/OpenShiftOidcWebSocketIT.java
  websockets/websocket-next-oidc/src/test/resources/test-realm-realm.json
  websockets/websocket-next/pom.xml
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/QuarkusQEUpgradeCheck.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/clients/PingPongClient.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/clients/UserDataClient.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/AdminChatWebsocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/AdminOnlyChatWebSocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/AuthenticatedChatWebSocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/ChatWebSocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/ConcurrentBlockingWebSocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/CustomSerializationWebsocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/FailingWebsocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/NativeSerializationWebsocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/ParentWebSocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/PingPongWebSocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/PropertiesSecuredWebSocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/ReactiveWebsocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/SerialBlockingWebSocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/UserDataWebSocket.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/resources/AuthenticatedChatResource.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/resources/PingPongResource.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/resources/TLSChatResource.java
  websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/resources/UserDataResource.java
  websockets/websocket-next/src/main/resources/application.properties
  websockets/websocket-next/src/main/resources/tls.properties
  websockets/websocket-next/src/test/java/io/quarkuss/ts/websocketNext/BaseWebSocketIT.java
  websockets/websocket-next/src/test/java/io/quarkuss/ts/websocketNext/OpenShiftWebSocketIT.java
  websockets/websocket-next/src/test/java/io/quarkuss/ts/websocketNext/TlsWebSocketIT.java
Labels: triage/flaky-test, triage/backport-3.20

#2365 Add coverage for QUARKUS-5611 (quarkus-oidc-client developer experience)
  README.md
  pom.xml
  security/keycloak-oidc-client-standalone/pom.xml
  security/keycloak-oidc-client-standalone/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/standalone/TokenResource.java
  security/keycloak-oidc-client-standalone/src/main/resources/application.properties
  security/keycloak-oidc-client-standalone/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/standalone/DevModeOidcClientDevServiceUserExperienceIT.java
  security/keycloak-oidc-client-standalone/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/standalone/DevModeOidcClientTokensIT.java
  security/keycloak-oidc-client-standalone/src/test/resources/oidc-client.properties
Labels: triage/backport-3.20

#2379 Use shorter names in GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/daily.yaml
Labels: triage/flaky-test

#2386 Adding test coverage for QUARKUS-5857 WebSockets Next send authorization headers from web browsers using JS clients
  websockets/websocket-next-oidc/src/main/resources/application.properties
  websockets/websocket-next-oidc/src/test/java/io/quarkuss/ts/websocketNext/VertxWebSocketClientIT.java
  websockets/websocket-next-oidc/src/test/java/io/quarkuss/ts/websocketNext/WebSocketNextBrowserAuthorizationIT.java
Labels: triage/backport-3.20

#2388 Avoid SQL application module failures in FIPS-enabled environment as DB2 JDBC driver is not FIPS-compatible
  sql-db/sql-app/pom.xml
Labels: triage/backport-3.20

#2381 Verify, that updates to 3.20 can be done automatically
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
  quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/QuarkusCli320UpdatesIT.java
  quarkus-cli/src/test/resources/quarkus315dependencyUpdates.csv
Labels: triage/backport-3.20

#2387 Add coverage for QUARKUS-5614 (`@PermissionAllowed` annotation on meta-annotation)
  README.md
  pom.xml
  security/permissions/pom.xml
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/annotations/CanCreate.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/annotations/CanReadAll.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/annotations/CanReadAllAndCreate.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/annotations/CanReadAllAndCreateInclusive.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/annotations/CanReadAndUpdate.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/annotations/CanReadAndUpdateCustomPermission.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/annotations/CanReadAndUpdateCustomPermissionInclusive.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/annotations/CanReadAndUpdateInclusive.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/annotations/CanReadMinimal.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/resources/ClassAnnotationPermissionAllowedInclusiveResource.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/resources/ClassAnnotationPermissionAllowedResource.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/resources/ClassCustomAnnotationPermissionAllowedInclusiveResource.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/resources/ClassCustomAnnotationPermissionAllowedResource.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/resources/CombinedCustomAndDefaultPermissionAllowedResource.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/resources/CustomAnnotationPermissionAllowedResource.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/resources/PermissionAllowedResource.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/resources/helpers/CustomPermission.java
  security/permissions/src/main/resources/application.properties
  security/permissions/src/test/java/io/quarkus/ts/openshift/security/basic/BasePermissionAllowedIT.java
  security/permissions/src/test/java/io/quarkus/ts/openshift/security/basic/CustomPermissionAllowedIT.java
  security/permissions/src/test/java/io/quarkus/ts/openshift/security/basic/OpenShiftCustomPermissionAllowedIT.java
  security/permissions/src/test/java/io/quarkus/ts/openshift/security/basic/OpenShiftPermissionAllowedIT.java
  security/permissions/src/test/java/io/quarkus/ts/openshift/security/basic/PermissionAllowedIT.java
Labels: triage/backport-3.20

#2394 Add coverage for QUARKUS-5617 (Support for two or more authentications for a single request)
  security/keycloak/pom.xml
  security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/MultiMechanismAuthenticationIT.java
  security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/OpenShiftMultiMechanismAuthenticationIT.java
  security/keycloak/src/test/resources/multi-mechanism.properties
Labels: triage/backport-3.20

#2396 Coverage for @AuthorizationPolicy
  security/basic/src/main/java/io/quarkus/ts/openshift/security/basic/CustomPolicyResource.java
  security/basic/src/main/java/io/quarkus/ts/openshift/security/policy/NameContainsB.java
  security/basic/src/main/java/io/quarkus/ts/openshift/security/policy/NameStartsWithA.java
  security/basic/src/main/resources/application.properties
  security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/BasicSecurityIT.java
Labels: triage/backport-3.20

#2401 Switch PostgreSQL in baremetal tests from 16 to 17
  pom.xml
  sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java
  sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/openshift/OpenShiftPostgresql12HibernateReactiveIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftPostgresql12DatabaseIT.java
Labels: triage/backport-3.20

#2400 Switch tests from MariaDB 10.11 to 11.4
  pom.xml
  security/jpa/src/test/java/io/quarkus/ts/security/jpa/MariaDbMd5JpaIT.java
  spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/MariaDBConstants.java
  spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/SpringWebQuteReactiveIT.java
  spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/SpringWebRestReactiveIT.java
  spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/openapi/SpringWebOpenApiReactiveIT.java
  spring/spring-web/src/test/java/io/quarkus/ts/spring/web/MariaDBConstants.java
  spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/OpenShiftSpringWebQuteIT.java
  spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/OpenShiftSpringWebRestIT.java
  spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/SpringWebQuteIT.java
  spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/SpringWebRestIT.java
  spring/spring-web/src/test/java/io/quarkus/ts/spring/web/openapi/OpenShiftSpringWebOpenApiIT.java
  spring/spring-web/src/test/java/io/quarkus/ts/spring/web/openapi/SpringWebOpenApiIT.java
  sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MariaDbDatabaseHibernateReactiveIT.java
  sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/MultiplePersistenceIT.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMariaDbTransactionGeneralUsageIT.java
  sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MariaDBPanacheResourceIT.java
  sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/OpenShiftMariaDBPanacheResourceIT.java
  sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MariaDBDatabaseIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbDevServicesUserExperienceIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MariaDBDatabaseIT.java
  sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMariaDBDatabaseIT.java
Labels: triage/backport-3.20

#2405 Add coverage for QUARKUS-5659 (Use Arc features in datasource extensions for eager startup and active/inactive)
  sql-db/multiple-pus/pom.xml
  sql-db/multiple-pus/src/main/java/io/quarkus/ts/sqldb/multiplepus/FungusResource.java
  sql-db/multiple-pus/src/main/java/io/quarkus/ts/sqldb/multiplepus/producer/DatasourceProducer.java
  sql-db/multiple-pus/src/main/java/io/quarkus/ts/sqldb/multiplepus/producer/DatasourceProducerResource.java
  sql-db/multiple-pus/src/main/resources/application.properties
  sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/AbstractCustomDatasourceProducerIT.java
  sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/AbstractMultiDatabaseActiveInactiveIT.java
  sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/CustomDatasourceProducerIT.java
  sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/MultiDatabaseActiveInactiveIT.java
  sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/OpenShiftCustomDatasourceProducerIT.java
  sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/OpenShiftMultiDatabaseActiveInactiveIT.java
  sql-db/multiple-pus/src/test/resources/datasource-producer.properties
Labels: triage/backport-3.20

#2409 Fix Keycloak OpenShift scenarios on IBM Power Z by using Red Hat Build of Keycloak in OpenShift
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/AbstractLogoutSinglePageAppFlowIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/AbstractOidcResponseFilterIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/AbstractOidcRestClientIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/LogoutSinglePageAppFlowIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OidcItUtils.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OidcResponseFilterIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OidcRestClientIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenApiStoreSchemaIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcResponseFilterIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcRestClientIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcSinglePageAppLogoutFlowIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/SecurityClaimsIT.java
  security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/TokenPropagationFilterIT.java
  security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/AbstractMultiMechanismAuthenticationIT.java
  security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/MultiMechanismAuthenticationIT.java
  security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/OpenShiftMultiMechanismAuthenticationIT.java
Labels: triage/backport-3.20

#2416 Fix Brotli4j scenarios with S390X and ppc64le architectures tested by our IBM partners
  http/http-advanced-reactive/pom.xml
Labels: triage/backport-3.20

#2415 Enhancement with permission checkers for WebSockets Next
  websockets/websocket-next/src/main/java/io/quarkus/ts/websockets/next/endpoints/AuthenticatedChatWebSocket.java
  websockets/websocket-next/src/main/resources/application.properties
  websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/BaseWebSocketIT.java
Labels: triage/backport-3.20

#2419 Use Red Hat Build of Keycloak for OpenShift tests and thus enable IBM partners to run more Keycloak tests
  http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHttpAdvancedReactiveIT.java
  http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/OpenShiftHttpAdvancedIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractLogoutSinglePageAppFlowIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractOidcRestClientIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/LogoutSinglePageAppFlowIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OidcRestClientIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenApiStoreSchemaIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcRestClientIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcSinglePageAppLogoutFlowIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/SecurityClaimsIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/TokenPropagationFilterIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/TokenUtils.java
Labels: triage/backport-3.20

#2412 QUARKUS-5658 WS.next + Otel tests
  websockets/websocket-next/pom.xml
  websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/BaseWebSocketIT.java
  websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/Client.java
  websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/OpenShiftWebSocketsNextOpenTelemetryIT.java
  websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/WebSocketsNextMetricsIT.java
  websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/WebSocketsNextOpenTelemetryIT.java
Labels: triage/backport-3.20

#2426 WS.next + metrics stabilization
  websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/WebSocketsNextMetricsIT.java
Labels: triage/backport-3.20

#2436 QUARKUS-5668 tests
  monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/PartiallyTraceableResource.java
  monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/UntraceableResource.java
  monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
Labels: triage/backport-3.20

#2438 Coverage for QUARKUS-5622 Support @PermissionAllowed for @BeanParam parameter
  security/permissions/README.md
  security/permissions/pom.xml
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/CommonFieldBeanParam.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/NestedStructureBeanParam.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/RecordBeanParam.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/SimpleBeanParam.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/permissions/AcquiredPermission.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/permissions/CommonFieldPermission.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/permissions/NestedBeanParamPermission.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/permissions/RecordBeanParamPermission.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/permissions/SimpleBeanParamPermission.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/resources/BeanParamResource.java
  security/permissions/src/main/java/io/quarkus/ts/openshift/security/basic/permissions/beanparam/resources/NestedStructureResource.java
  security/permissions/src/main/resources/application.properties
  security/permissions/src/main/resources/private-key.pem
  security/permissions/src/main/resources/public-key.pem
  security/permissions/src/test/java/io/quarkus/ts/openshift/security/basic/beanparam/BaseBeanParamPermissionsIT.java
  security/permissions/src/test/java/io/quarkus/ts/openshift/security/basic/beanparam/BeanParamPermissionIT.java
  security/permissions/src/test/java/io/quarkus/ts/openshift/security/basic/beanparam/JwtBeanParamPermissionIT.java
  security/permissions/src/test/java/io/quarkus/ts/openshift/security/basic/beanparam/OpenShiftBeanParamPermissionIT.java
Labels: triage/backport-3.20
