Repository quarkus-qe/quarkus-test-suite, pull requests merged in 2025-09, with the labels that each got.

#2608 Test enabling and disabling XA transaction recovery for individual datasources
  sql-db/narayana-transactions/src/main/resources/application.properties
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
  sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java
Labels: triage/backports-3.27

#2609 Add test coverage for QUARKUS-6263 OIDC Health Checks
  security/keycloak-oidc-client-extended/pom.xml
  security/keycloak-oidc-client-extended/src/main/resources/application.properties
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractHealthCheckIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractMultiTenantHealthCheckIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractOidcHealthCheckErrorStatusIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/MultiTenantHealthCheckIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OidcHealthCheckErrorStatusIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OidcHealthCheckIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftMultiTenantHealthCheckIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcHealthCheckErrorStatusIT.java
  security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcHealthCheckIT.java
  security/keycloak-oidc-client-extended/src/test/resources/health-enabled.properties
  security/keycloak-oidc-client-extended/src/test/resources/health-management.properties
Labels: triage/backports-3.27

#2638 Add test coverage for #47458 Add Metrics and Logs to OTel Capabilities
  monitoring/micrometer-opentelemetry/src/test/java/io/quarkus/ts/monitoring/micrometeropentelemetry/test/DevModeOtelCapabilitiesIT.java
Labels: triage/backport-3.20, triage/backports-3.27

#2627 Add coverage of QUARKUS-6262 - XML constraints and method overriding
  hibernate/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/database/XmlValidatedCustomer.java
  hibernate/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/ValidationResource.java
  hibernate/hibernate-reactive/src/main/resources/META-INF/validation.xml
  hibernate/hibernate-reactive/src/main/resources/META-INF/validation/constraints-customer.xml
  hibernate/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/AbstractHibernateValidatorIT.java
  hibernate/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MultiDatabaseHibernateReactiveIT.java
  hibernate/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MySQLHibernateValidatorDisabledIT.java
  hibernate/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/OracleHibernateValidatorDdlModeIT.java
  http/rest-client-reactive/pom.xml
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/validation/UserProcessingService.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/validation/UserProcessingServiceBean.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/validation/UserValidationResource.java
  http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/validation/ValidatedUser.java
  http/rest-client-reactive/src/main/resources/application.properties
  http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/UserProcessingValidationIT.java
Labels: triage/backports-3.27

#2644 Ensure annotation processor respect depmgmt
  pom.xml
Labels: triage/backport-3.20, triage/backports-3.27

#2649 Update to 3.27 Quarkus branch
  .github/actions/prepare-quarkus-cli/action.yml
  .github/workflows/ci.yml
  build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java
  external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java
  pom.xml
Labels: triage/flaky-test

#2655 Bump Elastic to 9.1.4
  pom.xml
Labels: triage/backports-3.27

#2650 Test Hibernate offline startup
  hibernate/hibernate-offline-startup/README.MD
  hibernate/hibernate-offline-startup/pom.xml
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/defaults/orm/Article.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/defaults/orm/CustomCredentialsProvider.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/defaults/orm/CustomTenantResolver.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/defaults/orm/RequestScopedData.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/defaults/rest/DatabaseManagementResource.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/defaults/rest/NewspapersResource.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/ownconnection/orm/Article.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/ownconnection/orm/CustomTenantConnectionResolver.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/ownconnection/orm/CustomTenantResolver.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/ownconnection/rest/DatabaseManagementResource.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/pu/ownconnection/rest/NewspapersResource.java
  hibernate/hibernate-offline-startup/src/main/java/io/quarkus/ts/hibernate/startup/offline/rest/PingResource.java
  hibernate/hibernate-offline-startup/src/main/resources/application.properties
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/AbstractHibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/Db2HibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/DevModeHibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/FixedPortResourceBuilder.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/HibernateReactiveOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/MariaDBHibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/MySqlDBHibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/OpenShiftMariaDBHibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/OpenShiftMySqlDBHibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/OpenShiftPostgreSqlHibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/OpenTelemetryHibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/OracleHibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/SqlServerHibernateOfflineStartupIT.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/reactive/ReactiveArticle.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/reactive/ReactiveDatasourceCredentialProvider.java
  hibernate/hibernate-offline-startup/src/test/java/io/quarkus/ts/hibernate/startup/offline/test/reactive/ReactiveResource.java
  hibernate/hibernate-offline-startup/src/test/resources/hibernate-reactive.properties
  hibernate/hibernate-offline-startup/src/test/resources/mysql-init.sql
  hibernate/hibernate-offline-startup/src/test/resources/mysql-my-conf.config
Labels: triage/backports-3.27

#2665 Disabling Consul on OCP tests due to bug in container
  properties/src/test/java/io/quarkus/ts/properties/consul/OpenShiftConsulConfigSourceIT.java
Labels: triage/backport-3.15, triage/backport-3.20, triage/backport-3.27

#2662 Coverage for QUARKUS-6243 - execute HQL queries using DevUI
  hibernate/hibernate-orm/src/main/java/io/quarkus/qe/hibernate/hql/Address.java
  hibernate/hibernate-orm/src/main/java/io/quarkus/qe/hibernate/hql/DevUIJsonRpcClient.java
  hibernate/hibernate-orm/src/main/java/io/quarkus/qe/hibernate/hql/HQLConsoleClient.java
  hibernate/hibernate-orm/src/main/java/io/quarkus/qe/hibernate/hql/OrderItem.java
  hibernate/hibernate-orm/src/main/java/io/quarkus/qe/hibernate/hql/Orders.java
  hibernate/hibernate-orm/src/main/resources/application.properties
  hibernate/hibernate-orm/src/main/resources/test-hql-pu-import-script.sql
  hibernate/hibernate-orm/src/test/java/io/quarkus/qe/hibernate/AbstractHQLConsoleIT.java
  hibernate/hibernate-orm/src/test/java/io/quarkus/qe/hibernate/DevModeMySQLHQLConsoleIT.java
  hibernate/hibernate-orm/src/test/java/io/quarkus/qe/hibernate/DevModePostgresqlHQLConsoleIT.java
  hibernate/hibernate-orm/src/test/resources/mysql.properties
Labels: triage/backport-3.27
